[package]
name = "google-maps-places"
version = "0.1.0"
edition = "2018"

exclude = [
  "test/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.4", features = ["json"] }
rust_decimal = "1.15"
rust_decimal_macros = "1.15"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
mockito = "0.30.0"
